### ISSUE TITLE
NannyCam not bringing up webserver?  Xtreme FW 0052

### ISSUE THREAD

**Issue by CtrlAltDel-Irl** [eried/FlipperZeroMayhem#30]
Hi,

Nannycam seems to load fine on Flipper showing login details but browser fails to load 192.168.4.1 and bring up image.
I can successfully ping the ip address though from a terminal.

**Comment by CtrlAltDel-Irl** [comment]
OK feeling rather stupid now.  Works perfectly in Chrome or Chromium browsers.
Firefox does not work.

**Comment by eried** [comment]
Oh, thats good to know. The reliability of NannyCam is highly dependant on the device (i.e. I have not found why sometimes is just unreliable) so it is a valid concern eitherway. 

But I will close this issue for now since is "solved" on your side. I hope to make this app more reliable in the future tho
