### ISSUE TITLE
Writing Documentation

### ISSUE THREAD

**Issue by FatherDivine** [eried/FlipperZeroMayhem#37]
Hi @eried. I would like to start giving back by writing documentation for the wiki. As outlined:

> There is a lot of missing documentation about all the features, so it is really important to write clean and detailed instructions for them. In this current wiki, you can modify or add new content with a normal Github account.

Currently, it seems that the option is disabled. I tried cloning and sending as a push, but I don't have access as well and I found it impossible to make a pull request using the wiki. The wiki is separate from the actual repo. 

So is it possible add me as a collaborator or whatnot to edit pages in the wiki? Below is my first update to Troubleshooting (I use vscode to edit markdown):

`## The ESP32 does not output any serial messages, nor it is able to be programmed, seems to be dead

You might have an unit with a different pinout, check the [known issues](Known-issues#esp32cam-extra-gnd).

## I can't select the Mayhem v2's CC1101 (external radio) in the Sub-GHz app.

If you are unable to toggle the external radio in the Flipper Zero's Sub-Ghz app (located under "Radio Settings > Module"), try changing the below settings in your "CFW Settings". 

The below is written using RogueMaster firmware, and as such your speed may vary depending upon firmware used. The CFW is "Custom Firmware Settings" and is an extra menu separate of the Flipper Zero's "Settings" menu.

1.) Click "CFW Settings".<br>
2.) Navigate to "Protocols".<br>
3.) Make sure "SPI CC1101 Handle" is set to "Default 4". If it says "Extra 7" the external radio will not work! 
5.) Make sure the "SPI NRF24 Handle" is set to "Default 4".<br>
6.) Go back and check if External is set as the Module in the Sub-Ghz App. It should automatically change to external upon plugging in the Mayhem V2 module.<br>`

Thanks.

**Comment by eried** [comment]
Oh that is awesome! I enabled the edit now. On a parent project (portapack mayhem) there was some massive spamming and many of the devs got kick out due some bogus reports so I decided to block the wiki edit for a while. 

Now it should be enabled again. Go ahead with the edits 👍 🥇 

That entry is perfect. I can comment a bit more about the overall situation based on people using the board, they mostly struggle in 3 things (this are 99% of the cases):

1. Updating the board, making the board enter "download mode"
2. Compiling/getting the app to work (usual issue is they are selecting the wrong app)
3. Figuring out what is wrong (when they assembled the board themselves)... which makes it difficult for me to help since it can be anything.
